### ISSUE TITLE
要是没有没数据怎么给值

### ISSUE THREAD

**Issue by Puppy-Love** [mychoices/Jgraph#11]

**Comment by Puppy-Love** [comment]
change数据 数据量不同还报错！！！！！！ 那要好几个数据量不同的 那不是要new 好几个chart，好奇葩的罗技！没有数据也报错，非要传个为零数据才能显示表格！！！！ 哎~不知道是不是我理解的不够

**Comment by huojk** [comment]
确实会这样，作者都没有好好维护这个项目

**Comment by 5hmlA** [comment]
项目不合适 直接使用，只是提供一个实现的思路而已
